import { useLocalSearchParams, router } from "expo-router";
import { useState } from "react";
import { Pressable, ScrollView, StyleSheet, Text, TextInput, View } from "react-native";

const restaurants = [
  { name: "Bukhara Kitchen", rating: "4.8", items: [["Chicken Biryani", "420"], ["Chicken Karahi", "1250"], ["Seekh Kebab", "650"]] },
  { name: "Lahore Tandoor House", rating: "4.6", items: [["Mutton Karahi", "1850"], ["Chicken Tikka", "520"]] },
];

export default function Dashboard() {
  const { role = "customer" } = useLocalSearchParams<{ role: string }>();
  const [cart, setCart] = useState<string[]>([]);
  const [online, setOnline] = useState(false);
  const [paid, setPaid] = useState(false);
  const [language, setLanguage] = useState<"en" | "ur">("en");
  const isUr = language === "ur";
  const title = role === "restaurant" ? (isUr ? "ریسٹورنٹ ڈیش بورڈ" : "Restaurant Dashboard") : role === "rider" ? (isUr ? "رائیڈر سینٹر" : "Rider Center") : role === "admin" ? (isUr ? "ایڈمن کنٹرول" : "Admin Control") : (isUr ? "آسان فوڈ" : "Easy Food");

  if (role === "restaurant") return <Shell title={title} language={language} setLanguage={setLanguage}><Stats labels={["Today Sales", "Orders", "Commission", "Settlement"]} values={["Rs. 48,650", "18", "2.5%", "Daily"]}/><Section title="Incoming Orders"><Info text="New orders appear here with accept, preparing and ready actions."/><Action text="Accept sample order"/></Section><Section title="Menu"><Info text="Chicken Biryani • Rs. 420 • Available"/><Info text="Chicken Karahi • Rs. 1,250 • 10% offer"/><Action text="Manage categories & menu"/></Section><Section title="Settlement"><Info text="Daily settlement • COD commission is tracked as outstanding balance."/></Section></Shell>;
  if (role === "rider") return <Shell title={title} language={language} setLanguage={setLanguage}><View style={s.hero}><Text style={s.kicker}>Daily access</Text><Text style={s.heroTitle}>Rs. 50 entry fee</Text><Text style={s.muted}>Pay once per day to receive delivery offers.</Text><Pressable style={s.primary} onPress={() => {setPaid(true);setOnline(true)}}><Text style={s.primaryText}>{paid ? "✓ Paid today" : "Pay Rs. 50"}</Text></Pressable></View><Stats labels={["Earnings", "Deliveries", "Rating", "Tracking"]} values={["Rs. 8,420", "24", "5.0 ★", online ? "Active" : "Off"]}/><Section title="Delivery availability">{online ? <><Info text="Order EF-1024 • Bukhara Kitchen • 3.2 km"/><Action text="Accept delivery"/></> : <Info text="Go online after paying the daily fee to receive orders."/>}</Section></Shell>;
  if (role === "admin") return <Shell title={title} language={language} setLanguage={setLanguage}><Stats labels={["Customers", "Restaurants", "Riders", "Orders"]} values={["1,284", "126", "348", "4,862"]}/><Stats labels={["Revenue", "Commission", "COD outstanding", "Rider fees"]} values={["Rs. 2.84M", "Rs. 184K", "Rs. 76K", "Rs. 17.4K"]}/><Section title="Announcement"><TextInput placeholder="Maintenance announcement..." style={s.input}/><View style={s.row}><Action text="All"/><Action text="Customers"/><Action text="Restaurants"/><Action text="Riders"/></View></Section><Section title="Operations"><Info text="Cities • Restaurants • Riders • Payments • Refunds • Complaints • Reviews • Settlements • Audit logs"/></Section></Shell>;
  return <Shell title={title} language={language} setLanguage={setLanguage}><View style={s.hero}><Text style={s.kicker}>🇵🇰 Pakistan-wide</Text><Text style={s.heroTitle}>{isUr ? "اچھا کھانا ایک ٹیپ دور" : "Good food is one tap away"}</Text><Text style={s.muted}>{isUr ? "قریب کے ریسٹورنٹس تلاش کریں اور آسانی سے آرڈر کریں۔" : "Find nearby restaurants and order with COD or online payment."}</Text></View><TextInput placeholder={isUr ? "ریسٹورنٹ یا کھانا تلاش کریں..." : "Search restaurants or food..."} style={s.input}/>{restaurants.map(r => <Section key={r.name} title={`${r.name} • ★ ${r.rating}`}>{r.items.map(([name, price]) => <View key={name} style={s.item}><View><Text style={s.itemName}>{name}</Text><Text style={s.muted}>Rs. {price}</Text></View><Pressable style={s.add} onPress={() => setCart([...cart, name])}><Text style={s.addText}>+ Add</Text></Pressable></View>)}</Section>)}<Section title={`Cart (${cart.length})`}><Info text={cart.length ? cart.join(" • ") : "Your cart is empty."}/><Action text="Checkout • COD / Online Payment"/></Section></Shell>;
}

function Shell({ title, children, language, setLanguage }: any) { return <ScrollView style={s.screen} contentContainerStyle={s.content}><View style={s.header}><View><Text style={s.brand}>Easy <Text style={{color:'#F26AA8'}}>Food</Text></Text><Text style={s.title}>{title}</Text></View><Pressable style={s.lang} onPress={() => setLanguage(language === 'en' ? 'ur' : 'en')}><Text>{language === 'en' ? 'اردو' : 'English'}</Text></Pressable></View>{children}<Pressable onPress={() => router.replace('/')}><Text style={s.switch}>Switch role</Text></Pressable></ScrollView>; }
function Section({title,children}:any){return <View style={s.section}><Text style={s.sectionTitle}>{title}</Text>{children}</View>}
function Info({text}:{text:string}){return <Text style={s.muted}>{text}</Text>}
function Action({text}:{text:string}){return <Pressable style={s.primary}><Text style={s.primaryText}>{text}</Text></Pressable>}
function Stats({labels,values}:{labels:string[],values:string[]}){return <View style={s.stats}>{labels.map((x,i)=><View style={s.stat} key={x}><Text style={s.muted}>{x}</Text><Text style={s.statValue}>{values[i]}</Text></View>)}</View>}
const s=StyleSheet.create({screen:{flex:1,backgroundColor:'#F7FBFD'},content:{padding:18,paddingTop:55},header:{flexDirection:'row',justifyContent:'space-between',alignItems:'flex-start',marginBottom:22},brand:{fontSize:17,fontWeight:'900',color:'#17202A'},title:{fontSize:27,fontWeight:'900',color:'#17202A',marginTop:5},lang:{backgroundColor:'#fff',borderRadius:10,padding:10},hero:{backgroundColor:'#E9F9FF',borderRadius:20,padding:22,marginBottom:14},kicker:{color:'#168BC1',fontWeight:'800'},heroTitle:{fontSize:28,fontWeight:'900',color:'#17202A',marginVertical:7},muted:{color:'#71808A',lineHeight:20},input:{backgroundColor:'#fff',borderWidth:1,borderColor:'#E0EAEE',borderRadius:12,padding:13,marginBottom:14},section:{backgroundColor:'#fff',borderRadius:17,padding:17,marginBottom:13},sectionTitle:{fontSize:17,fontWeight:'900',color:'#17202A',marginBottom:12},stats:{flexDirection:'row',flexWrap:'wrap',gap:9,marginBottom:13},stat:{backgroundColor:'#fff',borderRadius:14,padding:13,width:'48%',borderWidth:1,borderColor:'#E5EDF1'},statValue:{fontSize:20,fontWeight:'900',color:'#17202A',marginTop:5},primary:{backgroundColor:'#F26AA8',paddingVertical:12,paddingHorizontal:14,borderRadius:10,alignSelf:'flex-start',marginTop:12},primaryText:{color:'#fff',fontWeight:'900'},row:{flexDirection:'row',flexWrap:'wrap',gap:8},item:{flexDirection:'row',justifyContent:'space-between',alignItems:'center',paddingVertical:12,borderBottomWidth:1,borderBottomColor:'#EDF1F3'},itemName:{fontWeight:'800',color:'#17202A'},add:{backgroundColor:'#EAF8FD',padding:8,borderRadius:8},addText:{color:'#168BC1',fontWeight:'800'},switch:{textAlign:'center',color:'#168BC1',fontWeight:'800',padding:18}});
